apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-archiver-cronjob
  annotations:
    field.cattle.io/description: 'Consolidates hourly Fastly proxy logs from mutiple endpoints into a single file and uploads this to blob storage'
spec:
  # 15 minutes past the hour, every day
  schedule: '15 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: log-archiver-cronjob
              command:
                - /bin/bash
                - '-c'
                - >-
                  python consolidator_fastly.py -t $(date +%Y-%m-%dT%H -d "9 hours ago") -s azure-nginx,ria-ac3
              args:
              envFrom:
                - secretRef:
                    name: log-archiver-env-prod
